config/routes.rb
Rails.application.routes.draw do

  resources :forms
  devise_for :users


  root 'forms#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  namespace :ssp, defaults: { format: :jsonapi } do
    resources :forms
    resources :review_questions
  end
  #
  # draw :SSP
  #
  # root to: redirect("/forms")


end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  # before_action :set_response!, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]


  # GET /forms or /forms.json
  def index

    # respond_to do |format|
    #   format.html { render :index }
    #   # format.json do
    #   #   @forms = Form.all
    #   #   render json: forms
    #   # end
    # end
    #
    #

    @forms = Form.all
    @review_question = ReviewQuestion.all

    # case Form.user_id
    # when 1
    #   @userName = "Dom s"
    # when 2
    #   @userName = "Tommy L"
    # else
    #   @userName = "unknown"
    # end

    # render jsonapi: forms
    #
    # respond_to do |format|
    #   format.json { render(json: forms) }
    #   format.jsonapi { render(jsonapi: forms) }
    #   format.xml { render(xml: forms) }
    # end
  end

  # GET /forms/1 or /forms/1.json
  def show

    # render 'forms/:id'

    # forms = FormsController.all(params)
    # render jsonapi: forms
    # respond_to do |format|
    #   format.html {render('forms/:id')}
    #   format.json { render(json: forms) }
    #   format.jsonapi { render(jsonapi: forms) }
    #   format.xml { render(xml: forms) }
    # end
    puts "here"
    puts params
    @form = Form.find(params['id'])

  end

  # GET /forms/new
  def new
    @form = Form.new
    @review_question = ReviewQuestion.new

    # forms = FormsController.all(params)
    # render jsonapi: forms
    # respond_to do |format|
    #   format.json { render(json: forms) }
    #   format.jsonapi { render(jsonapi: forms) }
    #   format.xml { render(xml: forms) }
  end

  # GET /forms/1/edit
  def edit
    @form = Form.find(params['id'])
  end

  # POST /forms or /forms.json
  def create
    @form = Form.new

    respond_to do |format|
      if @form.save!
        format.html { redirect_to @form, notice: "Form was successfully created." }
        format.json { render :show, status: :created, location: @form }
        # format.jsonapi { render :show, status: :created, location: @review_question}
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
      # if @review_question.save!
      #   format.html { redirect_to '/forms', notice: "RQ was successfully created." }
      #   format.json { render :show, status: :created, location: @review_question }
      #   # format.jsonapi { render :show, status: :created, location: @review_question}
      # else
      #   format.html { render :new, status: :unprocessable_entity }
      #   format.json { render json: @review_question.errors, status: :unprocessable_entity }
      # end
    end
    render '/forms'
  end

  # PATCH/PUT /forms/1 or /forms/1.json
  def update
    @form = Form.find(params['id'])



    # respond_to do |format|
    #   if @form.update(form_params)
    #     format.html { redirect_to @form, notice: "Form was successfully updated." }
    #     format.json { render :show, status: :ok, location: @form }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @form.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /forms/1 or /forms/1.json
  def destroy
    @form = Form.find(params['id'])
    num = params['id']
    @form.destroy
    redirect_to '/forms'

    # respond_to do |format|
    #   format.html { redirect_to forms_url, notice: "Form was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def form_params
      params.require(:form).permit(:user_id, :q1_total, :q2_total, :q3_total, :q4_total, :q5_total, :total_points, :git_link)
    end

    private
    #
    # def all
    #   connection = SQLite3::Database.new 'db/development.sqlite3'
    #   connection.results_as_hash = true
    #   connection.execute("SELECT * FROM forms")
    # end

end

app/controllers/ssp/forms_controller.rb
module Ssp
  class FormsController < ApplicationController
  skip_forgery_protection
  def index
    # forms = FormResource.all(params)
    # respond_with(forms)

    render jsonapi: FormResource.all(params)
  end

  def show
    # form = FormResource.find(params)
    # respond_with(form)


    render jsonapi: FormResource.find(params)
  end

  def create
    puts 'bellend'
    puts params

    create_params = params.to_unsafe_h
    create_params[:data][:attributes][:user_id] = current_user.id
    puts create_params
    form = FormResource.build(create_params)
    # puts create_params

    if form.save
      render jsonapi: form, status: 201
    else
      render jsonapi_errors: form
    end
  end

  def update
    form = FormResource.find(params)

    if form.update_attributes
      render jsonapi: form
    else
      render jsonapi_errors: form
    end
  end

  def destroy
    form = FormResource.find(params)

    if form.destroy
      render jsonapi: { meta: {} }, status: 200
    else
      render jsonapi_errors: form
    end
  end
  end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_with(model: @form, local: true) do |f| %>
  <%# if f.errors.any? %>
<!--    <div id="error_explanation">-->
<!--      <h2><%#= pluralize(f.errors.count, "error") %> prohibited this f from being saved:</h2>-->

<!--      <ul>-->
        <%# f.errors.full_messages.each do |message| %>
<!--          <li><%#= message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <% total = @form.q1_total %>
    <%# props = 0 %>
    <%= react_component 'RQuestion' %>
    <%= f.label :q1_total %>
    <%= f.number_field :q1_total, value: total %>
  </div>

  <div class="field">
    <%= f.label :q2_total %>
    <%= f.number_field :q2_total %>
  </div>

  <div class="field">
    <%= f.label :q3_total %>
    <%= f.number_field :q3_total %>
  </div>

  <div class="field">
    <%= f.label :q4_total %>
    <%= f.number_field :q4_total %>
  </div>

  <div class="field">
    <%= f.label :q5_total %>
    <%= f.number_field :q5_total %>
  </div>

  <div class="field">
    <%= f.label :total_points %>
    <%= f.number_field :total_points %>
  </div>

  <div class="field">
    <%= f.label :git_link %>
    <%= f.text_field :git_link %>
  </div>

  <div>
    <%= f.number_field :user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

app/views/forms/edit.html.erb
<h1>Editing Form</h1>

<%= render 'form', form: @form %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Forms</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>User</th>
      <th>Q1 total</th>
      <th>Q2 total</th>
      <th>Q3 total</th>
      <th>Q4 total</th>
      <th>Q5 total</th>
      <th>Total points</th>
      <th>Git link</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @forms.each do |form| %>
      <tr>
        <td><%= form.id %></td>
        <td><%= case form.user_id
              when 1
                'Dom Samphier'
              when 2
                 'Tom Luce'
              else
                'unknown'
            end %></td>
        <td><%= form.q1_total %></td>
        <td><%= form.q2_total %></td>
        <td><%= form.q3_total %></td>
        <td><%= form.q4_total %></td>
        <td><%= form.q5_total %></td>
        <td><%= form.total_points %></td>
        <td><%= form.git_link %></td>
        <td><%= link_to 'Show', form %></td>
        <% if current_user.present? && form.user_id === current_user.id %>
          <td><%= link_to 'Edit', edit_form_path(form) %></td>
          <td><%= link_to 'Destroy', form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <td><%= react_component 'Delete', props: form.id %></td>
        <% else %>
          <td></td>
          <td></td>
        <% end %>
      </tr>
    <% end %>
    <tr>
      <td><h4>ReviewQuestion</h4></td>
    </tr>
    <tr>
      <th>ID</th>
      <th>Form ID</th>
      <th>coding for coverage</th>
    </tr>
  <% @review_question.each do |reviewQuestion| %>
    <tr>
      <td><%= reviewQuestion.id %></td>
      <td><%= reviewQuestion.form_id %></td>
      <td><%= reviewQuestion.coding_for_coverage %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<% if current_user.present? %>
  <%= react_component 'CheckUserID', props: current_user %>
<% end %>
<br>

<%= link_to 'New Form', new_form_path %>

<br />

<%= link_to 'Edit Profile', edit_user_registration_path %>

<% if user_signed_in? %>
  <%= link_to 'Sign Out', destroy_user_session_path, method: 'delete' %>
<% else %>
  <%= link_to 'Sign In', new_user_session_path, method: 'get' %>
<% end %>

<%#= react_component 'TestFunction' %>

<br />

app/views/forms/new.html.erb
<h1>New Form</h1>

<%= react_component 'forms/New' %>

<%#= render 'form' %>

<%= link_to 'Back', forms_path %>

app/views/forms/show.html.erb
<p id="notice"><%= notice %></p>

<!--<p>-->
<!--  <strong>User:</strong>-->
  <%#= @form.user_id %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Q1 total:</strong>-->
  <%#= @form.q1_total %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Q2 total:</strong>-->
  <%#= @form.q2_total %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Q3 total:</strong>-->
  <%#= @form.q3_total %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Q4 total:</strong>-->
  <%#= @form.q4_total %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Q5 total:</strong>-->
  <%#= @form.q5_total %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Total points:</strong>-->
  <%#= @form.total_points %>
<!--</p>-->

<!--<p>-->
<!--  <strong>Git link:</strong>-->
  <%#= @form.git_link %>
<!--</p>-->

<% case Form.user_id
    when 1
      used = 'Dom Samphier'
    when 2
      used = 'Tom Luce'
    else
      used = 'unknown'
    end %>

<%= react_component 'forms/Show', id: @form.id, user: used  %>



<%= link_to 'Edit', edit_form_path(@form) %> |
<%= link_to 'Back', forms_path %>